- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3 e o Virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: true
      

    - name: Instalando as dependências do projeto
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework


    - name: Iniciando o projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'

      